
CREATE PROCEDURE MY_FUN
	@A INT, @B INT
AS 
BEGIN
	DECLARE @TEMPLATE INT
	IF @A > @B
	BEGIN 
		SELECT @TEMPLATE = @A, @A = @B, @B = @TEMPLATE
	END

	WHILE @B % @A != 0
	BEGIN
		SELECT @TEMPLATE = @A, @A = @B % @A, @B = @TEMPLATE
	END
	PRINT N'Ước chung lớn nhất: ' + CAST(@A AS VARCHAR)
END

EXECUTE MY_FUN 30, 3
