  SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS FullName, CONVERT(VARCHAR, NGSINH, 105) AS NgaySinh
  FROM NHANVIEN
  WHERE YEAR(NGSINH) Between 1960 and 1965;
 
  SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS FullName ,YEAR(GETDATE())-YEAR(NGSINH) AS Tuoi
  FROM NHANVIEN;
  
  SELECT TENPHG, HONV + ' ' + TENLOT + ' ' + TENNV AS FullName,
		 CONVERT(VARCHAR, NG_NHANCHUC,105) AS 'NGAY SINH', COUNT(MANV) NHANVIEN
  FROM PHONGBAN INNER JOIN NHANVIEN
		ON (NHANVIEN.MANV = PHONGBAN.TRPHG) AND (PHONGBAN.MAPHG = NHANVIEN.PHG)
  GROUP BY TENPHG, NG_NHANCHUC, MANV, HONV, TENLOT,TENNV
  