SELECT UPPER(HONV) AS HoNV,
	   LOWER(TENLOT) AS Tenlot,
	   LOWER(LEFT(TENNV, 1)) + UPPER(SUBSTRING(TENNV,2, 1)) + LOWER(SUBSTRING(TENNV, 3, LEN(TENNV))) AS TenNV,
	   SUBSTRING(DCHI, CHARINDEX(' ', DCHI), CHARINDEX(',', DCHI) - CHARINDEX( ' ',DCHI)) AS DiaChi 
FROM NHANVIEN;

SELECT TENPHG AS TenPhong, CONVERT(VARCHAR, NG_NHANCHUC, 105) AS 'dd/mm/yyyy', COUNT((MANV)) AS SLNV
FROM PHONGBAN INNER JOIN  NHANVIEN 
	ON PHONGBAN.MAPHG = NHANVIEN.PHG
GROUP BY MAPHG, TENPHG, NG_NHANCHUC


		





