SELECT TENNV AS TENNV, LUONG AS LUONG, TENPHG AS TENPHONG, COUNT(TENNV) AS SL
From NHANVIEN INNER JOIN  PHONGBAN
ON  NHANVIEN.PHG = PHONGBAN.MAPHG 
WHERE LUONG > (SELECT AVG(LUONG)FROM NHANVIEN)
GROUP BY LUONG, TENNV, TENPHG



