
--BAI1-A
CREATE TRIGGER CheckLuong1500
	ON NHANVIEN
	FOR INSERT, UPDATE
AS
	IF(SELECT LUONG FROM inserted)<15000
	BEGIN
		PRINT N'Lương < 15000'
		ROLLBACK TRANSACTION
	END

--BAI1-B

CREATE TRIGGER VALIDAGE
	ON NHANVIEN
	FOR INSERT
AS
	DECLARE @AGE INT
	SELECT @AGE = DATEDIFF(YEAR, NgSinh, GETDATE())+1 FROM inserted
	
	IF @AGE < 18 OR @AGE > 65
	BEGIN
		PRINT N'Tuôi của nhân viên không hợp lệ 18<= age <=65'
		ROLLBACK TRANSACTION
	END

--BAI1-C

CREATE TRIGGER UPDATEADDRESS
	ON NHANVIEN
	FOR UPDATE
AS
	IF EXISTS (SELECT DCHI FROM inserted WHERE DCHI LIKE '%HCM')
	BEGIN
		PRINT N'Không thể cập nhật nhân viên ở HCM'
		ROLLBACK TRANSACTION
	END
