SELECT * FROM NHANVIEN DECLARE @DEMO TABLE (Phong INT, LUONGTB FLOAT)
INSERT INTO @DEMO 
	SELECT PHG, AVG(LUONG) AS LUONGTB FROM NHANVIEN GROUP BY PHG
SELECT TENNV, LUONG AS LuongTB, IIF(LUONG < LUONGTB , 'Tang luong', 'Khong tang luong') AS 'Tinh Trang'
FROM NHANVIEN INNER JOIN @DEMO 
ON PHG = Phong;

SELECT * FROM NHANVIEN DECLARE @TEST TABLE (Phong INT, LUONGTB FLOAT)
INSERT INTO @DEMO 
	SELECT PHG, AVG(LUONG) AS LUONGTB FROM NHANVIEN GROUP BY PHG
SELECT TENNV, LUONG AS LuongTB, IIF(LUONG < LUONGTB , 'Nhan Vien', 'Truong Phong') AS 'Tinh Trang'
FROM NHANVIEN INNER JOIN @DEMO 
ON PHG = Phong

SELECT TENNV = CASE PHAI
	WHEN 'Nam' THEN 'Mr.' + [TENNV]
	WHEN N'Nữ' THEN 'Ms.' + [TENNV]
END
FROM NHANVIEN

SELECT TENNV, LUONG, 'Thue' = CASE
	WHEN LUONG BETWEEN 0 AND 25000 THEN lUONG*0.1
	WHEN LUONG BETWEEN 25000 AND 30000 THEN lUONG*0.12
	WHEN LUONG BETWEEN 30000 AND 40000 THEN lUONG*0.15
	WHEN LUONG BETWEEN 40000 AND 50000 THEN lUONG*0.20
	ELSE LUONG * 0.25
END
FROM NHANVIEN		