SELECT * FROM PHONGBAN;
BEGIN TRY
	INSERT INTO PHONGBAN(TENPHG,MAPHG,TRPHG, NG_NHANCHUC)
		VALUES (N'Kế hoạch', '1', '001','2022-01-01');
	PRINT N'Thêm dữ liệu thành công';
END TRY

BEGIN CATCH
	PRINT N'Error: Chèn dữ  liệu không thành công';
END CATCH;


BEGIN TRY
	DECLARE @chia FLOAT
	SET @chia = 5 /0;
END TRY

BEGIN CATCH
	DECLARE @ERRORMESSAGE VARCHAR(2048), @ERRORSEVERITY INT, @ERRORSTATE INT
	SELECT @ERRORMESSAGE = ERROR_MESSAGE(),
		   @ERRORSEVERITY = ERROR_SEVERITY(),
		    @ERRORSTATE = ERROR_STATE();
			RAISERROR (@ERRORMESSAGE, @ERRORSEVERITY, @ERRORSTATE)
END CATCH

