--BAI2-A
CREATE PROCEDURE outputName
	@MANV VARCHAR(3)
AS
	
BEGIN	
	SELECT * FROM NHANVIEN WHERE MANV = @MANV
END
EXECUTE outputName '003';

--BAI2-B
SELECT COUNT(MANV) as SL, TENPHG , MADA
FROM NHANVIEN
	INNER JOIN PHONGBAN ON NHANVIEN.PHG = PHONGBAN.MAPHG
	INNER JOIN DEAN ON DEAN.PHONG = PHONGBAN.MAPHG
WHERE MADA = 2 AND DDIEM_DA = 'Nha Trang'
GROUP BY TENPHG, MADA


--BAI2-C
ALTER PROCEDURE CountQuantityStaff
	@MANV INT
AS
BEGIN	
	SELECT COUNT(MANV) as SL, TENPHG , MADA
FROM NHANVIEN
	INNER JOIN PHONGBAN ON NHANVIEN.PHG = PHONGBAN.MAPHG
	INNER JOIN DEAN ON DEAN.PHONG = PHONGBAN.MAPHG
WHERE MADA = @MANV
GROUP BY TENPHG, MADA
END
EXECUTE CountQuantityStaff 1;

--BAI2-D
SELECT *
FROM NHANVIEN
	INNER JOIN PHONGBAN ON PHONGBAN.MAPHG = NHANVIEN.PHG 
	LEFT OUTER JOIN THANNHAN ON THANNHAN.MA_NVIEN = NHANVIEN.MANV
WHERE THANNHAN.MA_NVIEN IS NULL AND TRPHG = '005'

--BAI2-E



CREATE PROCEDURE BAI2E
	@MANV VARCHAR(5), @MAPB VARCHAR(5)
AS
	
BEGIN	
	
	IF EXISTS (SELECT * FROM NHANVIEN WHERE MANV = '002' AND PHG = '2')
		PRINT N'Nhân viên' + ' ' + @MANV + ' ' + 'có trong phòng ban'  + @MAPB
	ELSE 
		PRINT N'Nhân viên'+ ' ' + @MANV + ' ' + 'không có trong phòng ban'  + @MAPB
END
EXECUTE BAI2E '002', '4';








