--BAI3-A
CREATE PROCEDURE THEMPHONGBANMOI
	@TenPhg NVARCHAR(20), @MaPhg INT, @TrPhg NVARCHAR(10), @NgNhanChuc DATE
AS 
BEGIN
	IF EXISTS (SELECT * FROM PHONGBAN WHERE MAPHG = @MaPhg)
	BEGIN
		PRINT N'Mã phòng ban đã tồn tại: '
		return;
	END

	INSERT INTO PHONGBAN(TENPHG, MAPHG, TRPHG, NG_NHANCHUC)
	VALUES(@TenPhg, @MaPhg, @TrPhg, @NgNhanChuc)
END
EXECUTE THEMPHONGBANMOI 'IT', 12, '005', '2002-11-29';


--BAI3-B
CREATE PROCEDURE CAPNHATPHONGBAN
	@TenPhgCu NVARCHAR(15), @TenPhg NVARCHAR(15), @MaPhg INT, @TrPhg NVARCHAR(10), @NgNhanChuc DATE
AS 
BEGIN
	UPDATE.PHONGBAN
		SET TENPHG = @TenPhg, MAPHG = @MaPhg, TRPHG = @TrPhg, NG_NHANCHUC = @NgNhanChuc
		WHERE TENPHG = @TenPhgCu
END
EXECUTE CAPNHATPHONGBAN 'CNTT', 'IT', 10, '005', '2002-11-29';

--BAI3-C
CREATE PROCEDURE INSERTNV 
	@HO NVARCHAR(15), @TENLOT NVARCHAR(15), @TENNV NVARCHAR(15), @MANV NVARCHAR(3),@NGAYSINH DATETIME, @DIACHI NVARCHAR(30), @PHAI NVARCHAR(3),
	@LUONG FLOAT, @MA_NQL NVARCHAR(3), @PHG INT

AS
BEGIN
	IF NOT EXISTS (SELECT * FROM PHONGBAN WHERE TENPHG LIKE 'IT')
	BEGIN
		PRINT N'Nhân viên phải là phòng IT'
		RETURN;
	END
	IF @LUONG < 25000 
	SET @MA_NQL = '009'
	ELSE 
	BEGIN
		SET @MA_NQL = '005'
	END
	DECLARE @AGE INT = DATEDIFF(YEAR, @NGAYSINH, GETDATE())
	IF @PHAI LIKE 'NAM' AND @AGE > 65 AND @AGE < 18
	BEGIN
		PRINT N' Nam phải từ 18 - 65'
		RETURN
	END 
	ELSE IF @PHAI LIKE N'Nữ' AND @AGE > 60 AND @AGE < 18
	BEGIN
		PRINT N' Nam phải từ 18 - 60'
		RETURN
	END
	INSERT INTO NHANVIEN(HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG)
	VALUES(@HO, @TENLOT, @TENNV, @MANV, @NGAYSINH, @DIACHI, @PHAI, @LUONG, @MA_NQL, @PHG)
END
EXECUTE INSERTNV N'Phạm', N'Văn', N'Tân', '005', '2002-1-1', N'291 Hồ Văn Huê, TP HCM', 'Nam', 25000, '005', 5